-- Rebuild the OpenCraft knowledge graph in Bahasa Indonesia, sourced from
-- ocraft.id (services, tech, methodology, case studies), LinkedIn (enterprise
-- voice & principles), and X/Threads/Instagram (casual voice & positioning).
-- Supersedes the English seed in 013. Idempotent: clears and rebuilds 'opencraft'.
delete from public.brand_knowledge_nodes where brand_slug = 'opencraft';

insert into public.brand_knowledge_nodes (brand_slug, type, label, description, color, icon) values
('opencraft','brand','OpenCraft','Transformasi AI untuk operasional enterprise — senior-led. Bandung, Indonesia.','#6366f1','🛠️'),
('opencraft','positioning','Transformasi AI untuk operasional enterprise','Tagline utama di ocraft.id.','#f43f5e','🎯'),
('opencraft','positioning','Masih kerja manual? Kami automate dengan AI','Tagline di X, Threads & Instagram — lebih cepat, efisien, scalable.','#f43f5e','⚡'),
('opencraft','positioning','Senior-led: operator untuk kerja setelah pilot','Bukan cuma demo — operator senior untuk fase setelah pilot.','#f43f5e','🧭'),
('opencraft','positioning','Workflow terpetakan, sistem terdeploy','Strategi & rollout tetap berdekatan.','#f43f5e','🗺️'),
('opencraft','positioning','Bukan hype, ini kerja nyata','Otomasi alur kerja AI untuk tim operasi.','#f43f5e','✊'),
('opencraft','layanan','Otomasi Customer Service','Agent AI di WhatsApp & Telegram: jawab instan, selesaikan FAQ & order, eskalasi ke tim.','#0ea5e9','💬'),
('opencraft','layanan','Internal Knowledge AI','Asisten RAG privat yang menjawab dari SOP, manual & tiket Anda — dengan sumber terkutip.','#0ea5e9','📚'),
('opencraft','layanan','Otomasi Content Creator','Satu brief jadi video pendek siap-posting & banner on-brand, diadaptasi per platform.','#0ea5e9','🎬'),
('opencraft','layanan','AI Transformation','Strategi, arsitektur workflow, dan implementasi end-to-end.','#0ea5e9','🧠'),
('opencraft','layanan','Automated Leads','Otomasi pencarian & kualifikasi leads.','#0ea5e9','🧲'),
('opencraft','layanan','Reviews Automation','Otomasi pengumpulan & respons review pelanggan.','#0ea5e9','⭐'),
('opencraft','layanan','Social Media Automation','Otomasi produksi konten & distribusi sosial media.','#0ea5e9','📣'),
('opencraft','tech','LangGraph',null,'#38bdf8','🔗'),
('opencraft','tech','LangChain',null,'#38bdf8','⛓️'),
('opencraft','tech','RAG Systems',null,'#38bdf8','📖'),
('opencraft','tech','OpenAI',null,'#38bdf8','🤖'),
('opencraft','tech','Model Prediktif',null,'#38bdf8','📈'),
('opencraft','tech','Otomasi Workflow',null,'#38bdf8','⚙️'),
('opencraft','proses','Audit Workflow (1–2 minggu)',null,'#f59e0b','🔍'),
('opencraft','proses','Desain Sistem & Integrasi (minggu 3–6)',null,'#f59e0b','🏗️'),
('opencraft','proses','Testing & Training (1–2 minggu)',null,'#f59e0b','🧪'),
('opencraft','proses','Deployment Production',null,'#f59e0b','🚀'),
('opencraft','proses','Engagement 4–8 minggu (enterprise besar 3–6 bulan)',null,'#f59e0b','🗓️'),
('opencraft','prinsip','Demo ≠ deployment',null,'#ec4899','🚧'),
('opencraft','prinsip','Adoption direncanakan sejak hari pertama',null,'#ec4899','📅'),
('opencraft','prinsip','Change management & libatkan tim non-teknis',null,'#ec4899','🤝'),
('opencraft','prinsip','Disiplin workflow',null,'#ec4899','🧩'),
('opencraft','prinsip','Jawaban bisa ditelusuri ke sumber (auditable)',null,'#ec4899','🔎'),
('opencraft','prinsip','Data bersih: garbage in, garbage out',null,'#ec4899','🧹'),
('opencraft','prinsip','Privasi data: tanpa training model pihak ketiga',null,'#ec4899','🔒'),
('opencraft','audiens','Pemimpin operasional',null,'#f97316','👔'),
('opencraft','audiens','Tim enterprise',null,'#f97316','🏢'),
('opencraft','audiens','Tim non-teknis & stakeholder',null,'#f97316','👥'),
('opencraft','audiens','Startup & bisnis Indonesia',null,'#f97316','🇮🇩'),
('opencraft','studi_kasus','Berjodoh — platform matching berbasis AI','Consumer AI workflow.','#22c55e','💞'),
('opencraft','studi_kasus','Beruang — platform intelijen keuangan','Sinyal live, kesadaran portofolio yang lebih tenang.','#22c55e','🐻'),
('opencraft','channel','Website ocraft.id',null,'#10b981','🌐'),
('opencraft','channel','LinkedIn — Opencraft',null,'#10b981','💼'),
('opencraft','channel','X — @opencraftdev',null,'#10b981','🐦'),
('opencraft','channel','Threads — @opencraft.id',null,'#10b981','🧵'),
('opencraft','channel','Instagram — @opencraft.dev',null,'#10b981','📸'),
('opencraft','channel','WhatsApp & Telegram',null,'#10b981','📱'),
('opencraft','tone','Formal ''Anda'' (LinkedIn / enterprise)',null,'#a855f7','🎩'),
('opencraft','tone','Kasual ''gw/lo'' (X, Threads, IG)',null,'#a855f7','😎'),
('opencraft','tone','Anti-hype, fokus kerja nyata',null,'#a855f7','🔧'),
('opencraft','topik','Enterprise AI',null,'#14b8a6','🏛️'),
('opencraft','topik','AI Adoption',null,'#14b8a6','📈'),
('opencraft','topik','Digital Transformation',null,'#14b8a6','🔄'),
('opencraft','topik','Knowledge Management',null,'#14b8a6','📚'),
('opencraft','topik','Change Management',null,'#14b8a6','🔁'),
('opencraft','topik','Data Quality',null,'#14b8a6','🧹'),
('opencraft','topik','LLM',null,'#14b8a6','🧠');

with n as (select label, id from public.brand_knowledge_nodes where brand_slug='opencraft')
insert into public.brand_knowledge_edges (brand_slug, source_id, target_id, relation, weight)
select 'opencraft', s.id, t.id, e.relation, e.weight
from (values
  ('OpenCraft','Transformasi AI untuk operasional enterprise','diposisikan sebagai',3),
  ('OpenCraft','Masih kerja manual? Kami automate dengan AI','diposisikan sebagai',2),
  ('OpenCraft','Senior-led: operator untuk kerja setelah pilot','diposisikan sebagai',2),
  ('OpenCraft','Workflow terpetakan, sistem terdeploy','diposisikan sebagai',2),
  ('OpenCraft','Bukan hype, ini kerja nyata','diposisikan sebagai',2),
  ('OpenCraft','Otomasi Customer Service','menawarkan',3),
  ('OpenCraft','Internal Knowledge AI','menawarkan',3),
  ('OpenCraft','Otomasi Content Creator','menawarkan',3),
  ('OpenCraft','AI Transformation','menawarkan',3),
  ('OpenCraft','Automated Leads','menawarkan',2),
  ('OpenCraft','Reviews Automation','menawarkan',2),
  ('OpenCraft','Social Media Automation','menawarkan',2),
  ('OpenCraft','Demo ≠ deployment','berpegang pada',2),
  ('OpenCraft','Adoption direncanakan sejak hari pertama','berpegang pada',2),
  ('OpenCraft','Change management & libatkan tim non-teknis','berpegang pada',2),
  ('OpenCraft','Disiplin workflow','berpegang pada',2),
  ('OpenCraft','Jawaban bisa ditelusuri ke sumber (auditable)','berpegang pada',2),
  ('OpenCraft','Data bersih: garbage in, garbage out','berpegang pada',2),
  ('OpenCraft','Privasi data: tanpa training model pihak ketiga','berpegang pada',2),
  ('OpenCraft','Pemimpin operasional','melayani',3),
  ('OpenCraft','Tim enterprise','melayani',3),
  ('OpenCraft','Tim non-teknis & stakeholder','melayani',2),
  ('OpenCraft','Startup & bisnis Indonesia','melayani',2),
  ('OpenCraft','Berjodoh — platform matching berbasis AI','dibuktikan oleh',2),
  ('OpenCraft','Beruang — platform intelijen keuangan','dibuktikan oleh',2),
  ('OpenCraft','Website ocraft.id','hadir di',2),
  ('OpenCraft','LinkedIn — Opencraft','hadir di',2),
  ('OpenCraft','X — @opencraftdev','hadir di',2),
  ('OpenCraft','Threads — @opencraft.id','hadir di',2),
  ('OpenCraft','Instagram — @opencraft.dev','hadir di',2),
  ('OpenCraft','WhatsApp & Telegram','hadir di',1),
  ('OpenCraft','Formal ''Anda'' (LinkedIn / enterprise)','bersuara',2),
  ('OpenCraft','Kasual ''gw/lo'' (X, Threads, IG)','bersuara',2),
  ('OpenCraft','Anti-hype, fokus kerja nyata','bersuara',2),
  ('OpenCraft','Enterprise AI','membahas',1),
  ('OpenCraft','AI Adoption','membahas',1),
  ('OpenCraft','Digital Transformation','membahas',1),
  ('OpenCraft','Knowledge Management','membahas',1),
  ('OpenCraft','Change Management','membahas',1),
  ('OpenCraft','Data Quality','membahas',1),
  ('OpenCraft','LLM','membahas',1),
  ('OpenCraft','Audit Workflow (1–2 minggu)','metodologi',2),
  ('OpenCraft','Engagement 4–8 minggu (enterprise besar 3–6 bulan)','timeline',1),
  ('Audit Workflow (1–2 minggu)','Desain Sistem & Integrasi (minggu 3–6)','lanjut ke',2),
  ('Desain Sistem & Integrasi (minggu 3–6)','Testing & Training (1–2 minggu)','lanjut ke',2),
  ('Testing & Training (1–2 minggu)','Deployment Production','lanjut ke',2),
  ('Internal Knowledge AI','RAG Systems','dibangun dengan',2),
  ('Internal Knowledge AI','LangChain','dibangun dengan',2),
  ('Internal Knowledge AI','OpenAI','dibangun dengan',2),
  ('Otomasi Customer Service','LangGraph','dibangun dengan',2),
  ('Otomasi Customer Service','LangChain','dibangun dengan',1),
  ('Otomasi Customer Service','OpenAI','dibangun dengan',1),
  ('AI Transformation','Otomasi Workflow','dibangun dengan',2),
  ('AI Transformation','Model Prediktif','dibangun dengan',1),
  ('Otomasi Content Creator','OpenAI','dibangun dengan',1),
  ('Otomasi Content Creator','Otomasi Workflow','dibangun dengan',1),
  ('Otomasi Customer Service','WhatsApp & Telegram','dikirim via',2),
  ('Pemimpin operasional','AI Transformation','tertarik pada',2),
  ('Tim enterprise','Internal Knowledge AI','tertarik pada',2),
  ('Tim non-teknis & stakeholder','AI Transformation','tertarik pada',1),
  ('Startup & bisnis Indonesia','Otomasi Customer Service','tertarik pada',1),
  ('Formal ''Anda'' (LinkedIn / enterprise)','LinkedIn — Opencraft','dipakai di',2),
  ('Kasual ''gw/lo'' (X, Threads, IG)','X — @opencraftdev','dipakai di',1),
  ('Kasual ''gw/lo'' (X, Threads, IG)','Threads — @opencraft.id','dipakai di',1),
  ('Kasual ''gw/lo'' (X, Threads, IG)','Instagram — @opencraft.dev','dipakai di',1)
) as e(src,tgt,relation,weight)
join n s on s.label = e.src
join n t on t.label = e.tgt;
